### ISSUE TITLE
Endless fainting spell loop

### ISSUE THREAD

**Issue by Inglix** [Turnovus/Integrated-Genes#2]
The following code can create an endless loop of fainting spells for pawns with the Terrified gene. This is because the condition on line 62 can be evaluated to true regardless of how old that LogEntry is, because the age of the entry isn't checked until line 67. You need to swap the two conditionals around so that it checks the age of the entry first before evaluating whether it's a hostile action towards the pawn.

https://github.com/Turnovus/Integrated-Genes/blame/5bce736bb7d65128411c1054a39bfe7b6939617d/Common/Source/IntegratedGenes/MentalBreakWorkers/MentalBreakWorker_FaintingSpell.cs#L60-L69

**Comment by Turnovus** [comment]
You are correct, I will include a fix in the next release. Would you like to submit a pull request to the development branch, or would you rather that I simply take care of it?

**Comment by Turnovus** [comment]
Fixed in mod version 1.5.0
